language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer selfupdate && composer --version
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit
